### ISSUE TITLE
re: hacking

### ISSUE THREAD

**Issue by killfire179** [Nerfednijt/nxte-FIB-heist#1]
![image](https://user-images.githubusercontent.com/61851747/161379687-1cda8106-80d0-4983-98c0-ed1aed963ddd.png)
after doing all the hacks i get to the lockers but they are saying the door lock still active

**Comment by Nerfednijt** [comment]
ill look into it now !

**Comment by killfire179** [comment]
okay thank you

**Comment by Nerfednijt** [comment]
yes i have and i couldnt find any issues while testing it myself

**Comment by Nerfednijt** [comment]
for better support with my scripts i recommend going to my discord :  https://discord.gg/z3TnPNQe

**Comment by Nick5M420** [comment]
im having the same issue, has anyone found a solution?

**Comment by Nerfednijt** [comment]
hello there , sorry for the delay ive been extremely busy , i will look into this tomorrow

**Comment by Nerfednijt** [comment]
Issue should be fixed :)
